import 'dotenv/config';

export default {
    PORT: process.env.PORT,
    SUPABASE_CONNECTION_STRING: process.env.SUPABASE_CONNECTION_STRING,
    SUPABASE_URL: process.env.SUPABASE_URL,
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    MONIFY_API_KEY: process.env.MONIFY_API_KEY,
    MONIFY_SECRET_KEY: process.env.MONIFY_SECRET_KEY,
    MONIFY_WALLET_ACCOUNT_NUMBER: process.env.MONIFY_WALLET_ACCOUNT_NUMBER,
    MONIFY_CONTRACT_CODE: process.env.MONIFY_CONTRACT_CODE,
    MONIFY_API_URL: process.env.MONIFY_API_URL,
    NOMBA_WEBHOOK_SIGNATURE: process.env.NOMBA_WEBHOOK_SIGNATURE
}